defaults:
  - _self_
  - ../base/data@data: default
  - ../base/algo@algo: bc_mee_policy
  - ../base/policy@policy: transformer_policy    # policy_name: BCTransformerPolicy, image encoder: resnet, fuse: transformer
  - ../base/train@train: default
  - ../base/eval@eval: default
  - ../base/env@env: default


experiment_dir: ???

hydra:
  run:
    dir: ./outputs/libero/${algo.algo_name}/transformer/${data.env_name}/ratio${data.train_ratio}/sigma${train.sigma}/mee_weight${train.mee_weight}/${now:%m%d}_${now:%H%M}_seed${train.seed}
  sweep:
    dir: ./outputs/libero/${algo.algo_name}/transformer/${data.env_name}/ratio${data.train_ratio}/sigma${train.sigma}/mee_weight${train.mee_weight}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    subdir: ${hydra.job.num}

wandb:
  use_wandb: false
  project: bc-mee-transformer
  name: ${data.env_name}_${algo.algo_name}_transformer_sigma${train.sigma}_mee_weight${train.mee_weight}_${now:%m%d}_${now:%H%M}_seed${train.seed}_ratio${data.train_ratio}_${hydra:job.num}
  group: ${data.env_name}_${algo.algo_name}_sigma${train.sigma}_mee_weight${train.mee_weight}_transformer
  dir: ./wandb/${env.env_type}/${algo.algo_name}/sigma${train.sigma}/mee_weight${train.mee_weight}/transformer/${data.env_name}/ratio${data.train_ratio}
